---
title: "TCGA Ovarian Cancer Survival Analysis - CDK11"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---
title: "Survival Analysis 2"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Ovarian Cancer

```{r}
# load my libraries
library(TCGAbiolinks)
library(survminer)
library(survival)
library(SummarizedExperiment)
library(tidyverse)
library(DESeq2)
library(pander)
```

```{r}
clin_ov <- GDCquery_clinic('TCGA-OV')
which(colnames(clin_ov) %in% c('vital_status', 'days_to_last_follow_up', 'days_to_death'))
clin_ov[,c(9,39,45)]
```

```{r}
table(clin_ov$vital_status)
```

```{r}
clin_ov$deceased <- ifelse(clin_ov$vital_status == 'Alive', FALSE, TRUE)

```

```{r}
clin_ov$overall_survival <- ifelse(clin_ov$vital_status == 'Alive', clin_ov$days_to_last_follow_up, clin_ov$days_to_death)
```

```{r}
query_ov <- GDCquery(
  project = 'TCGA-OV',
  data.category = 'Transcriptome Profiling',
  experimental.strategy = 'RNA-Seq',
  workflow.type = 'STAR - Counts',
  sample.type = 'Primary Tumor',
  data.type = 'Gene Expression Quantification',
  access = 'open'
  )

output_ov <- getResults(query_ov)

```

```{r}
#tumor_ov <- output_ov[output_ov$sample_type == 'Primary Tumor', 'cases'][1:50]
#tumor_ov
```

```{r}
query_ov <- GDCquery(
  project = 'TCGA-OV',
  data.category = 'Transcriptome Profiling',
  experimental.strategy = 'RNA-Seq',
  workflow.type = 'STAR - Counts',
  sample.type = 'Primary Tumor',
  data.type = 'Gene Expression Quantification',
  access = 'open'
  #barcode = tumor
  )
```

```{r}
# download my data
GDCdownload(query_ov)
```

```{r}
# get counts
tcga_ov_data <- GDCprepare(query_ov, summarizedExperiment = TRUE)
ov_matrix <- assay(tcga_ov_data, 'unstranded')
ov_matrix[1:10, 1:10]
```

```{r}
# extract raw data and store in matrix
gene_metadata_ov <- as.data.frame(rowData(tcga_ov_data))
coldata_ov <- as.data.frame(colData(tcga_ov_data))
```

```{r}
dds <- DESeqDataSetFromMatrix(countData = ov_matrix,
                              colData = coldata_ov,
                              design = ~ 1)

keep <- rowSums(counts(dds)) >= 10
dds <- dds[keep,]

vsd <- vst(dds, blind=FALSE)
ov_matrix_vst <- assay(vsd)
ov_matrix_vst[1:10, 1:10]
# vst means variance stabilized transformed counts
```

```{r}
# Get data for CDK11B only
ov_cdk11 <- ov_matrix_vst %>%
  as.data.frame() %>%
  rownames_to_column(var = 'gene_id') %>%
  gather(key = 'case_id', value = 'counts', -gene_id) %>%
  left_join(., gene_metadata_ov, by = 'gene_id') %>%
  filter(gene_name == 'CDK11B')
  
```

```{r}
# divide patients into low expression and high expression groups - I will be using the median value but you can use percentiles as well.  

median_value <- median(ov_cdk11$counts)

ov_cdk11$strata <- ifelse(ov_cdk11$counts >= median_value, 'HIGH', 'LOW')
```

```{r}
# Add all the information into one data frame
# remove additional characters in the case_id so that it matches with the submitter_id in the other data sets

ov_cdk11$case_id <- gsub('-01.*', '', ov_cdk11$case_id)
ov_cdk11 <- merge(ov_cdk11, clin_ov, by.x = 'case_id', by.y = 'submitter_id')
```

```{r}
# Survival Curve
fit <- survfit(Surv(overall_survival, deceased) ~ strata, data = ov_cdk11)
pander(fit)
```

```{r}
# Plot the survival curve
ggsurvplot(fit,
           data = ov_cdk11,
           pval = T,
           risk.table = T)


```

```{r}
# Use the survdiff function to compare between the 2 groups

fit2 <- survdiff(Surv(overall_survival, deceased) ~ strata, data = ov_cdk11)
pander(fit2)
```



 